version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/ticket
    environment:
      - FLASK_APP=ticket.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
